import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Sinha Education Point</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Sinha Education point</h1>
    </div>
  );
};

export default Home;
