import Head from "next/head";
import { Fragment } from "react";
import AboutPage from "../components/homepage/about";
import HeroPage from "../components/homepage/home";

const Home = () => {
  return (
    <Fragment>
      <Head>
        <title>Sinha Education Point</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroPage />
      <AboutPage />
    </Fragment>
  );
};

export default Home;
